version: '3.1'

services:
    web:
        container_name: php
        build:
            ./webserver/php
        volumes:
            - ./src:/var/www/html/
        ports:
            - "81:80"
        depends_on:
           - db
        links:
            - db


    db:
        image: mariadb
        container_name: mariadb-test
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: test

    adminer:
        container_name: adminer-test
        image: adminer
        ports:
            - 5542:8080
        depends_on:
            - db
        links:
            - db
